name: 'jdk-sbt-cache'
description: 'Checkout Code, Setup JDK and SBT Cache by SO'

inputs:
  token:
    required: true
    description: 'token'
  fetch-depth:
    required: false
    description: 'fetch-depth'
    default: 1
  ref:
    required: false
    description: 'ref'
    default: ''    
  jdk-distro:
    required: false
    description: 'jdk distro'
    default: 'adopt'
  jdk-version:
    required: false
    description: 'jdk version'
    default: '11'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
        

    - uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.jdk-distro }}
        java-version: ${{ inputs.jdk-version }}

    - uses: actions/cache@v3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier
          ~/.cache/coursier
        key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}

branding:
  icon: 'aperture'
  color: 'blue'
