name: 'jdk-sbt-cache'
description: 'Checkout Code, Setup JDK and SBT Cache by SO'

inputs:
  token:
    required: true
    description: 'token'
  fetch-depth:
    required: false
    description: 'fetch-depth'
    default: 1
  ref:
    required: false
    description: 'ref'
    default: ''    
  jdk-distro:
    required: false
    description: 'jdk distro'
    default: 'adopt'
  jdk-version:
    required: false
    description: 'jdk version'
    default: '11'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
        

    - uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.jdk-distro }}
        java-version: ${{ inputs.jdk-version }}
        cache: sbt
    - uses: sbt/setup-sbt@v1

branding:
  icon: 'aperture'
  color: 'blue'
